<?php

declare(strict_types=1);

namespace App\Services;

use App\Models\GameVersion;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\DB;

class RouteGraphService
{
    private const GRAPH_REVISION = 11;

    /**
     * Compute word counts per label from dialogue lines.
     * Uses the game's source language, falling back to English.
     *
     * @return array<string, int> label name => word count
     */
    public static function getWordCountsByLabel(GameVersion $version): array
    {
        $game = $version->game ?? $version->game()->first();
        $isoCode = $game?->source_language_id ?? 'eng';

        // Use length-based word count estimation instead of regexp_split_to_array.
        // The regex approach creates an array per row for the sole purpose of counting
        // elements, which is expensive in aggregate. The difference is negligible for
        // display purposes (word counts are approximate regardless).
        $rows = DB::table('version_dialogue_lines')
            ->join('unique_dialogue_texts', 'version_dialogue_lines.text_id', '=', 'unique_dialogue_texts.id')
            ->where('version_dialogue_lines.game_version_id', $version->id)
            ->where('version_dialogue_lines.iso_code', $isoCode)
            ->whereNotNull('version_dialogue_lines.context')
            ->groupBy('version_dialogue_lines.context')
            ->select([
                'version_dialogue_lines.context',
                DB::raw("SUM(
                    CASE WHEN trim(unique_dialogue_texts.text_content) = '' THEN 0
                    ELSE array_length(string_to_array(trim(unique_dialogue_texts.text_content), ' '), 1)
                    END
                ) as word_count"),
            ])
            ->get();

        $result = [];
        foreach ($rows as $row) {
            $result[$row->context] = (int) $row->word_count;
        }

        return $result;
    }

    public function buildGraph(GameVersion $version, bool $includeUnreachable = false): array
    {
        if ($includeUnreachable) {
            return $this->computeGraph($version, includeUnreachable: true);
        }

        if (is_array($version->route_graph_data) && ($version->route_graph_data['graph_revision'] ?? null) === self::GRAPH_REVISION) {
            return $version->route_graph_data;
        }

        // Fallback: compute and store if not pre-calculated or if the cached
        // graph was generated by an older plotting revision.
        return $this->computeAndStore($version);
    }

    public function computeAndStore(GameVersion $version): array
    {
        $graph = $this->computeGraph($version);
        $version->route_graph_data = $graph;
        $version->saveQuietly();

        return $graph;
    }

    public function computeGraph(GameVersion $version, bool $includeUnreachable = false): array
    {
        $labels = $version->routeLabels()->get();
        $edges = $version->routeEdges()->get();
        $menuChoices = $version->routeMenuChoices()->get();
        $variables = $version->routeVariables()->get();
        $variableChanges = $version->routeVariableChanges()->get();

        $wordCounts = self::getWordCountsByLabel($version);

        $edges = $this->removeUnreachableFallthroughEdges($edges);
        $edgeMapByFrom = $edges->groupBy('from_label');

        // Pre-index variable changes by label AND by context for fast lookup
        $varChangesByContext = [];
        foreach ($variableChanges as $vc) {
            $key = $vc->label.'|'.($vc->context ?? '');
            $varChangesByContext[$key][] = $vc;
        }
        $varChangesByLabel = $variableChanges->groupBy('label');
        $choicesByLabel = $menuChoices->groupBy('from_label');
        $labelNames = $labels->pluck('name')->flip();

        // Pre-index menu choices by from_label:target_label for O(1) lookup.
        $choiceLookup = [];
        foreach ($menuChoices as $mc) {
            if (! empty($mc->target_label)) {
                $choiceLookup[$mc->from_label.':'.$mc->target_label][] = $mc;
            }
        }

        $nodes = [];
        $processedEdges = [];
        $expandedLabels = [];
        $expandedEdgeReplacements = [];
        $expandedEndingReplacements = [];
        $additionalEndingNodes = [];

        foreach ($labels as $label) {
            $name = $label->name;
            $outgoingEdges = $edgeMapByFrom->get($name, collect());
            $isStart = $name === 'labels.start' || $name === 'start';
            $varChanges = $varChangesByLabel->get($name, collect());
            $nodeChoices = $choicesByLabel->get($name, collect());
            $continuationEdges = $outgoingEdges
                ->filter(fn ($e) => $e->edge_type !== 'menu_choice')
                ->reject(fn ($e) => $this->isDuplicateMenuChoiceEdge($e, $choiceLookup[$e->from_label.':'.$e->to_label] ?? []))
                ->values();
            $allTargetlessChoiceLines = $this->targetlessChoiceLines($nodeChoices);

            // Filter to meaningful choices: ones that change variables or branch to a target
            $meaningfulChoices = $nodeChoices->filter(function ($mc) use ($name, $varChangesByContext, $continuationEdges, $allTargetlessChoiceLines, $label) {
                if (! empty($mc->target_label)) {
                    return true;
                }
                $contextKey = $name.'|menu_choice:'.($mc->text ?? '');

                if (! empty($varChangesByContext[$contextKey])) {
                    return true;
                }

                if ((bool) $label->is_ending) {
                    return true;
                }

                return $this->getContinuationEdgesForChoice($mc, $continuationEdges, $allTargetlessChoiceLines)->isNotEmpty();
            });

            // Only collapse "function menus" (chapter select, gallery, etc.) into hub nodes.
            // Normal gameplay menus should always expand to show all choices.
            // Function menus are detected by label names, prompts, or choice patterns.
            $maxExpandedChoices = 10;

            // Get the prompt (question) for this menu early (needed for function menu detection)
            $firstChoice = $meaningfulChoices->first();
            $menuPrompt = $firstChoice?->prompt;
            $isFunctionMenu = $this->isFunctionMenu($name, $meaningfulChoices, $menuPrompt);

            if ($meaningfulChoices->isNotEmpty() && ($meaningfulChoices->count() <= $maxExpandedChoices || ! $isFunctionMenu)) {
                // This label has a manageable number of choices — expand into sub-graph
                $expandedLabels[$name] = true;
                $expandedEdgeReplacements[$name] = [];
                $menuPromptTranslations = $firstChoice?->prompt_translations;

                // Create the main label node (content before the choice)
                $nodes[] = [
                    'id' => $name,
                    'label' => $name,
                    'node_type' => 'label',
                    'is_ending' => false, // not an ending if it has choices
                    'is_start' => $isStart,
                    'has_menu_choice' => true,
                    'menu_prompt' => $menuPrompt,
                    'menu_prompt_translations' => $menuPromptTranslations,
                    'file_path' => $label->file_path,
                    'line_number' => $label->line_number,
                    'outgoing_count' => $meaningfulChoices->count(),
                    'word_count' => $wordCounts[$name] ?? 0,
                    'choices' => [],
                    'variable_changes' => $this->formatVarChanges($varChanges, excludeChoiceContexts: true),
                ];

                $menuChoiceLines = $meaningfulChoices
                    ->pluck('line_number')
                    ->filter(fn ($line) => $line !== null && (int) $line > 0)
                    ->map(fn ($line) => (int) $line)
                    ->unique()
                    ->sort()
                    ->values();
                $targetlessChoiceLines = $this->targetlessChoiceLines($meaningfulChoices);
                $syntheticEndingId = null;

                if ((bool) $label->is_ending) {
                    $syntheticEndingId = $this->syntheticEndingId($name);
                    $expandedEndingReplacements[$name] = $syntheticEndingId;

                    if (! isset($labelNames[$syntheticEndingId])) {
                        $additionalEndingNodes[$syntheticEndingId] = [
                            'id' => $syntheticEndingId,
                            'label' => $syntheticEndingId,
                            'node_type' => 'label',
                            'is_ending' => true,
                            'is_start' => false,
                            'has_menu_choice' => false,
                            'file_path' => $label->file_path,
                            'line_number' => $label->line_number,
                            'outgoing_count' => 0,
                            'word_count' => 0,
                            'choices' => [],
                            'variable_changes' => [],
                            'is_synthetic_ending' => true,
                        ];
                    }
                }

                foreach ($meaningfulChoices->values() as $i => $mc) {
                    $choiceId = $name.':choice_'.$i;
                    $choiceText = $mc->text ?? 'Choice '.($i + 1);

                    // Get variable changes for this specific choice (indexed lookup)
                    $choiceContext = 'menu_choice:'.($mc->text ?? '');
                    $contextKey = $name.'|'.$choiceContext;
                    $choiceVarChanges = $this->getVariableChangesForChoice(
                        $mc,
                        collect($varChangesByContext[$contextKey] ?? []),
                        $menuChoiceLines
                    );

                    // Build label with variable effects
                    $varSummary = $choiceVarChanges->map(function ($vc) {
                        $val = $vc->value;
                        // Simplify AST dump values for display
                        if (preg_match('/^Num\(n=(.+)\)$/', $val, $m)) {
                            $val = $m[1];
                        } elseif (preg_match("/^Str\(s='(.+)'\)$/", $val, $m)) {
                            $val = "'".$m[1]."'";
                        } elseif (preg_match("/^Name\(id='(.+?)'.*\)$/", $val, $m)) {
                            $val = $m[1];
                        }

                        return $vc->variable_name.' '.$vc->operation.' '.$val;
                    })->join(', ');

                    // Hard choice: has its own target. Soft choice: uses continuation edges.
                    $hasHardTarget = ! empty($mc->target_label);
                    $choiceContinuationEdges = $hasHardTarget
                        ? collect()
                        : $this->getContinuationEdgesForChoice($mc, $continuationEdges, $targetlessChoiceLines);
                    $usesSyntheticEnding = ! $hasHardTarget && $choiceContinuationEdges->isEmpty() && $syntheticEndingId !== null;
                    $outCount = $hasHardTarget ? 1 : ($usesSyntheticEnding ? 1 : $choiceContinuationEdges->count());

                    $nodes[] = [
                        'id' => $choiceId,
                        'label' => $choiceText,
                        'choice_text' => $choiceText,
                        'translations' => $mc->translations,
                        'var_summary' => $varSummary ?: null,
                        'node_type' => 'choice',
                        'is_ending' => false,
                        'is_start' => false,
                        'has_menu_choice' => false,
                        'file_path' => $mc->file_path,
                        'line_number' => $mc->line_number ?? 0,
                        'outgoing_count' => $outCount,
                        'word_count' => 0,
                        'choices' => [],
                        'variable_changes' => $this->formatVarChanges($choiceVarChanges, onlyContext: $choiceContext),
                        'parent_label' => $name,
                        'condition' => $mc->condition,
                    ];

                    // Edge from label to choice
                    $processedEdges[] = [
                        'id' => $name.':'.$choiceId.':choice',
                        'source' => $name,
                        'target' => $choiceId,
                        'edge_type' => 'choice',
                        'condition' => $mc->condition,
                    ];

                    if ($hasHardTarget) {
                        // Hard choice: direct edge to its target
                        $processedEdges[] = [
                            'id' => $choiceId.':'.$mc->target_label.':choice_target',
                            'source' => $choiceId,
                            'target' => $mc->target_label,
                            'edge_type' => 'choice_target',
                            'condition' => null,
                        ];
                    } else {
                        // Soft choice: connect only to continuation edges in the
                        // same menu segment. Connecting every targetless choice
                        // to every later label-level edge creates impossible
                        // route fanout for setup/chapter-select labels.
                        if ($usesSyntheticEnding) {
                            $processedEdges[] = [
                                'id' => $choiceId.':'.$syntheticEndingId.':return',
                                'source' => $choiceId,
                                'target' => $syntheticEndingId,
                                'edge_type' => 'return',
                                'condition' => null,
                            ];
                        } else {
                            foreach ($choiceContinuationEdges as $ce) {
                                $processedEdges[] = [
                                    'id' => $this->generatedChoiceEdgeId($choiceId, $ce),
                                    'source' => $choiceId,
                                    'target' => $ce->to_label,
                                    'edge_type' => $ce->edge_type,
                                    'condition' => $ce->condition,
                                ];
                                $expandedEdgeReplacements[$name][$this->edgeIdentity($ce)] = true;
                            }
                        }
                    }
                }
            } elseif ($meaningfulChoices->count() > $maxExpandedChoices) {
                // Too many choices to expand — render as a hub node
                // Don't mark as expanded so original edges are kept
                $nodes[] = [
                    'id' => $name,
                    'label' => $name,
                    'node_type' => 'hub',
                    'is_ending' => (bool) $label->is_ending,
                    'is_start' => $isStart,
                    'has_menu_choice' => true,
                    'hub_choice_count' => $meaningfulChoices->count(),
                    'file_path' => $label->file_path,
                    'line_number' => $label->line_number,
                    'outgoing_count' => $outgoingEdges->count(),
                    'word_count' => $wordCounts[$name] ?? 0,
                    'choices' => $meaningfulChoices->map(fn ($mc) => [
                        'text' => $mc->text,
                        'translations' => $mc->translations,
                        'target_label' => $mc->target_label,
                        'condition' => $mc->condition,
                    ])->values()->toArray(),
                    'variable_changes' => $this->formatVarChanges($varChanges, excludeChoiceContexts: true),
                ];
            } else {
                // Regular node without choices
                $nodes[] = [
                    'id' => $name,
                    'label' => $name,
                    'node_type' => 'label',
                    'is_ending' => (bool) $label->is_ending,
                    'is_start' => $isStart,
                    'has_menu_choice' => false,
                    'file_path' => $label->file_path,
                    'line_number' => $label->line_number,
                    'outgoing_count' => $outgoingEdges->count(),
                    'word_count' => $wordCounts[$name] ?? 0,
                    'choices' => [],
                    'variable_changes' => $this->formatVarChanges($varChanges, excludeChoiceContexts: true),
                ];
            }
        }

        foreach ($additionalEndingNodes as $node) {
            $nodes[] = $node;
        }

        // Process edges. Expanded labels keep original edges unless a generated
        // choice edge already represents that exact raw edge.
        foreach ($edges as $edge) {
            if (isset($expandedLabels[$edge->from_label])) {
                if ($edge->edge_type === 'menu_choice') {
                    continue;
                }

                $edgeKey = $this->edgeIdentity($edge);
                if (isset($expandedEdgeReplacements[$edge->from_label][$edgeKey])) {
                    continue;
                }

                if ($this->isDuplicateMenuChoiceEdge($edge, $choiceLookup[$edge->from_label.':'.$edge->to_label] ?? [])) {
                    continue;
                }
            }

            if ($this->isDuplicateMenuChoiceEdge($edge, $choiceLookup[$edge->from_label.':'.$edge->to_label] ?? [])) {
                continue;
            }

            $edgeData = [
                'id' => $this->routeEdgeId($edge),
                'source' => $edge->from_label,
                'target' => $edge->to_label,
                'edge_type' => $edge->edge_type,
                'condition' => $edge->condition,
                'file_path' => $edge->file_path,
                'line_number' => $edge->line_number,
            ];

            if ($edge->edge_type === 'menu_choice') {
                $matchingChoice = $this->findMatchingMenuChoice($edge, $choiceLookup[$edge->from_label.':'.$edge->to_label] ?? []);
                if ($matchingChoice) {
                    $edgeData['choice_text'] = $matchingChoice->text;
                    $edgeData['condition'] = $matchingChoice->condition;
                }
            }

            $processedEdges[] = $edgeData;
        }

        // Post-process: infer else conditions and deduplicate
        $processedEdges = $this->inferElseConditions($processedEdges);
        $nodes = $this->addMissingEndpointNodes($nodes, $processedEdges);
        if (! $includeUnreachable) {
            [$nodes, $processedEdges] = $this->filterReachableFromStart($nodes, $processedEdges);
        }

        // Leave disconnected script components disconnected. Fabricated bridge
        // edges make the map claim routes exist when Ren'Py control flow does
        // not actually connect them.

        // Pre-count variable changes by name
        $varChangeCounts = [];
        foreach ($variableChanges as $vc) {
            $varChangeCounts[$vc->variable_name] = ($varChangeCounts[$vc->variable_name] ?? 0) + 1;
        }

        $variableData = $variables->map(function ($v) use ($varChangeCounts) {
            return [
                'name' => $v->name,
                'default_value' => $v->default_value,
                'type' => $v->type,
                'change_count' => $varChangeCounts[$v->name] ?? 0,
            ];
        })->values()->toArray();

        $visibleNodeIds = collect($nodes)->pluck('id')->flip();
        $endings = $labels
            ->where('is_ending', true)
            ->pluck('name')
            ->reject(fn (string $name) => isset($expandedEndingReplacements[$name]))
            ->filter(fn (string $name) => isset($visibleNodeIds[$name]))
            ->values()
            ->toArray();

        foreach ($expandedEndingReplacements as $endingId) {
            if (isset($visibleNodeIds[$endingId]) && ! in_array($endingId, $endings, true)) {
                $endings[] = $endingId;
            }
        }

        return [
            'graph_revision' => self::GRAPH_REVISION,
            'includes_unreachable' => $includeUnreachable,
            'nodes' => $nodes,
            'edges' => $processedEdges,
            'variables' => $variableData,
            'endings' => $endings,
            'total_nodes' => count($nodes),
            'total_edges' => count($processedEdges),
            'has_graph_data' => true,
        ];
    }

    public function buildSimplifiedGraph(Collection $labels, Collection $edges, array $wordCounts = []): array
    {
        // Pre-index edges for O(1) lookup instead of O(n) per label
        $outgoing = [];
        $incoming = [];
        foreach ($labels as $label) {
            $outgoing[$label->name] = [];
            $incoming[$label->name] = [];
        }
        foreach ($edges as $edge) {
            $outgoing[$edge->from_label][] = $edge->to_label;
            $incoming[$edge->to_label][] = $edge->from_label;
        }

        $branchPoints = [];
        $chainNodes = [];

        foreach ($labels as $label) {
            $name = $label->name;
            $outCount = count($outgoing[$name] ?? []);
            $inCount = count($incoming[$name] ?? []);
            $isStart = $name === 'start' || $name === 'labels.start';
            $isEnding = (bool) $label->is_ending;

            if ($isStart || $isEnding || $outCount !== 1 || $inCount !== 1) {
                $branchPoints[$name] = true;
            } else {
                $chainNodes[$name] = true;
            }
        }

        $chains = [];
        $visited = [];

        foreach ($chainNodes as $name => $_) {
            if (isset($visited[$name])) {
                continue;
            }

            $chain = [$name];
            $visited[$name] = true;
            $current = $name;

            while (true) {
                $outs = $outgoing[$current] ?? [];
                if (count($outs) !== 1) {
                    break;
                }
                $next = $outs[0];
                if (isset($branchPoints[$next]) || isset($visited[$next])) {
                    break;
                }
                $chain[] = $next;
                $visited[$next] = true;
                $current = $next;
            }

            if (count($chain) > 1) {
                $chains[] = $chain;
            }
        }

        $simplifiedNodes = [];
        $labelToSimplified = [];

        // Pre-index labels by name for O(1) lookup
        $labelsByName = $labels->keyBy('name');

        foreach ($branchPoints as $name => $_) {
            $label = $labelsByName->get($name);
            $simplifiedNodes[] = [
                'id' => $name,
                'label' => $name,
                'type' => 'branch',
                'is_start' => $name === 'start' || $name === 'labels.start',
                'is_ending' => (bool) ($label->is_ending ?? false),
                'word_count' => $wordCounts[$name] ?? 0,
            ];
            $labelToSimplified[$name] = $name;
        }

        foreach ($chains as $chain) {
            $first = $chain[0];
            $collapsedId = 'chain_'.implode('_', array_slice($chain, 0, 3)).'_'.count($chain);
            $chainWordCount = array_sum(array_map(fn ($n) => $wordCounts[$n] ?? 0, $chain));

            $simplifiedNodes[] = [
                'id' => $collapsedId,
                'label' => count($chain).' nodes',
                'type' => 'chain',
                'chain_labels' => $chain,
                'first_label' => $first,
                'last_label' => $chain[count($chain) - 1],
                'is_start' => false,
                'is_ending' => false,
                'word_count' => $chainWordCount,
            ];

            foreach ($chain as $node) {
                $labelToSimplified[$node] = $collapsedId;
            }
        }

        $simplifiedEdges = [];
        $seen = [];

        foreach ($edges as $edge) {
            $sourceId = $labelToSimplified[$edge->from_label] ?? $edge->from_label;
            $targetId = $labelToSimplified[$edge->to_label] ?? $edge->to_label;

            if ($sourceId === $targetId) {
                continue;
            }
            $edgeKey = $sourceId.':'.$targetId.':'.$edge->edge_type;
            if (isset($seen[$edgeKey])) {
                continue;
            }
            $seen[$edgeKey] = true;
            $simplifiedEdges[] = [
                'id' => $edgeKey,
                'source' => $sourceId,
                'target' => $targetId,
                'edge_type' => $edge->edge_type,
            ];
        }

        return [
            'nodes' => $simplifiedNodes,
            'edges' => $simplifiedEdges,
            'chain_count' => count($chains),
        ];
    }

    private function edgeIdentity($edge): string
    {
        if (! empty($edge->id)) {
            return 'id:'.$edge->id;
        }

        return implode('|', [
            (string) ($edge->from_label ?? ''),
            (string) ($edge->to_label ?? ''),
            (string) ($edge->edge_type ?? ''),
            (string) ($edge->condition ?? ''),
            (string) ($edge->file_path ?? ''),
            (string) ($edge->line_number ?? ''),
        ]);
    }

    private function routeEdgeId($edge): string
    {
        if (! empty($edge->id)) {
            return 'route_edge:'.$edge->id;
        }

        return 'route_edge:'.md5($this->edgeIdentity($edge));
    }

    private function generatedChoiceEdgeId(string $choiceId, $edge): string
    {
        if (! empty($edge->id)) {
            return $choiceId.':route_edge:'.$edge->id;
        }

        return $choiceId.':route_edge:'.md5($this->edgeIdentity($edge));
    }

    private function syntheticEndingId(string $labelName): string
    {
        return $labelName.':ending';
    }

    private function targetlessChoiceLines(Collection $choices): Collection
    {
        return $choices
            ->filter(fn ($choice) => empty($choice->target_label))
            ->pluck('line_number')
            ->filter(fn ($line) => $line !== null && (int) $line > 0)
            ->map(fn ($line) => (int) $line)
            ->unique()
            ->sort()
            ->values();
    }

    private function getContinuationEdgesForChoice($choice, Collection $continuationEdges, Collection $menuChoiceLines): Collection
    {
        $choiceLine = (int) ($choice->line_number ?? 0);

        if ($choiceLine <= 0) {
            return $continuationEdges->count() === 1 ? $continuationEdges : collect();
        }

        $nextMenuLine = $menuChoiceLines->first(fn (int $line) => $line > $choiceLine);
        $segmentEdges = $continuationEdges
            ->filter(function ($edge) use ($choiceLine, $nextMenuLine) {
                $edgeLine = (int) ($edge->line_number ?? 0);

                return $edgeLine > $choiceLine && ($nextMenuLine === null || $edgeLine < $nextMenuLine);
            })
            ->values();

        if ($segmentEdges->isNotEmpty()) {
            return $segmentEdges;
        }

        if ($nextMenuLine === null && $continuationEdges->count() === 1) {
            return $continuationEdges;
        }

        return collect();
    }

    private function addMissingEndpointNodes(array $nodes, array $edges): array
    {
        $nodeIds = [];
        foreach ($nodes as $node) {
            $nodeIds[$node['id']] = true;
        }

        foreach ($edges as $edge) {
            foreach (['source', 'target'] as $key) {
                $id = $edge[$key] ?? null;
                if (! is_string($id) || $id === '' || isset($nodeIds[$id])) {
                    continue;
                }

                $nodes[] = [
                    'id' => $id,
                    'label' => $id,
                    'node_type' => 'label',
                    'is_ending' => false,
                    'is_start' => false,
                    'has_menu_choice' => false,
                    'file_path' => null,
                    'line_number' => 0,
                    'outgoing_count' => 0,
                    'word_count' => 0,
                    'choices' => [],
                    'variable_changes' => [],
                    'is_unresolved' => true,
                ];
                $nodeIds[$id] = true;
            }
        }

        return $nodes;
    }

    /**
     * Route maps should describe playable flow from the game's entry label.
     * Keep unrooted fixture graphs intact, but when a start node exists, hide
     * script fragments that Ren'Py cannot reach from that start path.
     *
     * @return array{0: array<int, array>, 1: array<int, array>}
     */
    private function filterReachableFromStart(array $nodes, array $edges): array
    {
        $nodeIds = [];
        $startIds = [];

        foreach ($nodes as $node) {
            $id = $node['id'] ?? null;
            if (! is_string($id) || $id === '') {
                continue;
            }

            $nodeIds[$id] = true;
            if (($node['is_start'] ?? false) || $id === 'start' || $id === 'labels.start') {
                $startIds[] = $id;
            }
        }

        if (empty($startIds)) {
            return [$nodes, $edges];
        }

        $adjacency = [];
        foreach ($edges as $edge) {
            $source = $edge['source'] ?? null;
            $target = $edge['target'] ?? null;

            if (! is_string($source) || ! is_string($target)) {
                continue;
            }

            if (! isset($nodeIds[$source], $nodeIds[$target])) {
                continue;
            }

            $adjacency[$source][] = $target;
        }

        $visited = [];
        $queue = [];
        foreach (array_unique($startIds) as $startId) {
            $visited[$startId] = true;
            $queue[] = $startId;
        }

        while ($queue !== []) {
            $current = array_shift($queue);
            foreach ($adjacency[$current] ?? [] as $target) {
                if (isset($visited[$target])) {
                    continue;
                }

                $visited[$target] = true;
                $queue[] = $target;
            }
        }

        $filteredNodes = array_values(array_filter(
            $nodes,
            fn (array $node) => isset($visited[$node['id'] ?? null])
        ));

        $filteredEdges = array_values(array_filter(
            $edges,
            fn (array $edge) => isset($visited[$edge['source'] ?? null], $visited[$edge['target'] ?? null])
        ));

        return [$filteredNodes, $filteredEdges];
    }

    private function getVariableChangesForChoice($choice, Collection $choiceVarChanges, Collection $menuChoiceLines): Collection
    {
        if ($choiceVarChanges->count() <= 1) {
            return $choiceVarChanges->values();
        }

        $choiceLine = (int) ($choice->line_number ?? 0);
        if ($choiceLine <= 0) {
            return $choiceVarChanges->values();
        }

        $nextMenuLine = $menuChoiceLines->first(fn (int $line) => $line > $choiceLine);
        $lineScopedChanges = $choiceVarChanges
            ->filter(function ($change) use ($choiceLine, $nextMenuLine) {
                $changeLine = (int) ($change->line_number ?? 0);

                return $changeLine > $choiceLine && ($nextMenuLine === null || $changeLine < $nextMenuLine);
            })
            ->values();

        return $lineScopedChanges->isNotEmpty()
            ? $lineScopedChanges
            : $choiceVarChanges->values();
    }

    private function findMatchingMenuChoice($edge, array $choices)
    {
        if (empty($choices)) {
            return null;
        }

        $edgeLine = (int) ($edge->line_number ?? 0);

        foreach ($choices as $choice) {
            if ((int) ($choice->line_number ?? 0) === $edgeLine) {
                return $choice;
            }
        }

        return $choices[0] ?? null;
    }

    private function isDuplicateMenuChoiceEdge($edge, array $choices): bool
    {
        if (empty($choices) || $edge->edge_type === 'menu_choice') {
            return false;
        }

        if (! in_array($edge->edge_type, ['jump', 'call', 'flow'], true)) {
            return false;
        }

        $edgeLine = (int) ($edge->line_number ?? 0);
        foreach ($choices as $choice) {
            $choiceLine = (int) ($choice->line_number ?? 0);
            $choiceEdgeType = $choice->edge_type ?: $edge->edge_type;

            if ($choiceEdgeType === $edge->edge_type && ($edgeLine <= 0 || $choiceLine <= 0 || $edgeLine >= $choiceLine)) {
                return true;
            }
        }

        return false;
    }

    private function removeUnreachableFallthroughEdges(Collection $edges): Collection
    {
        $terminalLineBySource = [];

        foreach ($edges as $edge) {
            if (! in_array($edge->edge_type, ['jump', 'return'], true)) {
                continue;
            }

            if (! $this->isUnconditional($edge->condition)) {
                continue;
            }

            $line = (int) ($edge->line_number ?? 0);
            if ($line <= 0) {
                continue;
            }

            $source = (string) $edge->from_label;
            $terminalLineBySource[$source] = min($terminalLineBySource[$source] ?? $line, $line);
        }

        if (empty($terminalLineBySource)) {
            return $edges->values();
        }

        return $edges
            ->reject(function ($edge) use ($terminalLineBySource) {
                if ($edge->edge_type !== 'flow') {
                    return false;
                }

                if (! $this->isUnconditional($edge->condition)) {
                    return false;
                }

                $terminalLine = $terminalLineBySource[(string) $edge->from_label] ?? null;
                if ($terminalLine === null) {
                    return false;
                }

                $line = (int) ($edge->line_number ?? 0);

                return $line > $terminalLine;
            })
            ->values();
    }

    private function isUnconditional(?string $condition): bool
    {
        $condition = trim((string) $condition);

        return $condition === '' || $condition === 'True';
    }

    /**
     * When a label has conditional edges alongside unconditional flow edges to
     * different targets, the flow edges are the implicit "else" case.
     * Also removes duplicate edges to the same target when a conditional version exists.
     */
    /**
     * When start can only reach a small subset of the graph, bridge to
     * disconnected components via synthetic edges.
     * This handles games that use screen-based navigation we can't statically resolve.
     */
    private function bridgeDisconnectedComponents(array $nodes, array $edges): array
    {
        if (empty($nodes) || empty($edges)) {
            return $edges;
        }

        $startId = null;
        $nodeIndex = [];
        foreach ($nodes as $n) {
            $nodeIndex[$n['id']] = $n;
            if ($n['is_start'] ?? false) {
                $startId = $n['id'];
            }
        }

        if (! $startId) {
            return $edges;
        }

        // Early exit: if start node is not a proper label node, skip bridging
        $startNode = $nodeIndex[$startId] ?? null;
        if (! $startNode || ($startNode['node_type'] ?? '') !== 'label') {
            return $edges;
        }

        // Iteratively bridge: BFS from start, find unreachable entry points, bridge, repeat
        $maxBridges = 20;
        for ($attempt = 0; $attempt < $maxBridges; $attempt++) {
            $adjacency = [];
            foreach ($edges as $e) {
                $adjacency[$e['source']][] = $e['target'];
            }

            $visited = [$startId => true];
            $queue = [$startId];
            // Track the last reachable menu-choice label during BFS
            $lastReachableMenuNode = $startId;
            while (! empty($queue)) {
                $current = array_shift($queue);
                foreach ($adjacency[$current] ?? [] as $target) {
                    if (! isset($visited[$target])) {
                        $visited[$target] = true;
                        $queue[] = $target;
                        // Track menu-choice labels as potential bridge sources
                        $targetNode = $nodeIndex[$target] ?? null;
                        if ($targetNode && ($targetNode['node_type'] ?? '') === 'label' && ($targetNode['has_menu_choice'] ?? false)) {
                            $lastReachableMenuNode = $target;
                        }
                    }
                }
            }

            if (count($visited) > count($nodes) * 0.95) {
                break; // Good enough
            }

            // Find unreachable label nodes (not choice/hub/ending sub-nodes) that have outgoing edges
            // These are likely game entry points we can't see
            $bestBridge = null;
            $bestOutgoing = 0;

            // Pre-index incoming edges by target for O(1) lookup instead of O(edges) per node
            $unreachableIncoming = [];
            foreach ($edges as $e) {
                if (! isset($visited[$e['target']])) {
                    $unreachableIncoming[$e['target']] = ($unreachableIncoming[$e['target']] ?? 0) + 1;
                }
            }

            foreach ($nodes as $n) {
                $id = $n['id'];
                if (isset($visited[$id])) {
                    continue;
                }
                if (($n['node_type'] ?? '') !== 'label') {
                    continue;
                }

                $outCount = count($adjacency[$id] ?? []);
                if ($outCount <= 0) {
                    continue;
                }

                // Prefer nodes with no incoming edges from unreachable nodes (true entry points)
                $hasUnreachableIncoming = ($unreachableIncoming[$id] ?? 0) > 0;

                $score = $outCount + ($hasUnreachableIncoming ? 0 : 1000);
                if ($score > $bestOutgoing) {
                    $bestOutgoing = $score;
                    $bestBridge = $id;
                }
            }

            if (! $bestBridge) {
                break;
            }

            $bridgeSource = $lastReachableMenuNode;

            $edges[] = [
                'id' => $bridgeSource.':'.$bestBridge.':bridge',
                'source' => $bridgeSource,
                'target' => $bestBridge,
                'edge_type' => 'flow',
                'condition' => null,
            ];
        }

        return $edges;
    }

    private function inferElseConditions(array $edges): array
    {
        // Group edges by source
        $bySource = [];
        foreach ($edges as $i => $edge) {
            $bySource[$edge['source']][] = $i;
        }

        foreach ($bySource as $indices) {
            if (count($indices) < 2) {
                continue;
            }

            // Find conditions on conditional edges from this source
            $conditions = [];
            $unconditionalFlowIndices = [];
            foreach ($indices as $i) {
                $e = $edges[$i];
                $isUnconditional = empty($e['condition']) || $e['condition'] === 'True';
                if (! $isUnconditional) {
                    $conditions[] = $e['condition'];
                } elseif (in_array($e['edge_type'], ['flow', 'jump'])) {
                    $unconditionalFlowIndices[] = $i;
                }
            }

            if (empty($conditions) || empty($unconditionalFlowIndices)) {
                continue;
            }

            // Remove unconditional flow edges that duplicate conditional edges
            // only when the conditionals do not actually branch to another
            // target. If conditionals branch elsewhere, the fall-through edge
            // is the implicit else path and must remain visible.
            $conditionalTargets = [];
            foreach ($indices as $i) {
                $cond = $edges[$i]['condition'] ?? null;
                if (! empty($cond) && $cond !== 'True') {
                    $conditionalTargets[$edges[$i]['target']] = true;
                }
            }
            $hasConditionalBranch = count($conditionalTargets) > 1;
            foreach ($unconditionalFlowIndices as $j => $i) {
                if (! $hasConditionalBranch && isset($conditionalTargets[$edges[$i]['target']])) {
                    unset($edges[$i]);
                    unset($unconditionalFlowIndices[$j]);
                }
            }

            // For remaining unconditional flow edges, infer the else condition
            if (! empty($conditions) && ! empty($unconditionalFlowIndices)) {
                $conditionParts = array_map(fn (string $condition) => '('.$condition.')', array_values(array_unique($conditions)));
                $elseCondition = 'not ('.implode(' or ', $conditionParts).')';

                foreach ($unconditionalFlowIndices as $i) {
                    if (isset($edges[$i])) {
                        $edges[$i]['condition'] = $elseCondition;
                    }
                }
            }
        }

        return array_values($edges);
    }

    private function formatVarChanges(Collection $varChanges, ?string $onlyContext = null, bool $excludeChoiceContexts = false): array
    {
        $filtered = $varChanges;

        if ($onlyContext !== null) {
            $filtered = $filtered->filter(fn ($vc) => $vc->context === $onlyContext);
        }

        if ($excludeChoiceContexts) {
            $filtered = $filtered->reject(fn ($vc) => str_starts_with((string) $vc->context, 'menu_choice:'));
        }

        return $filtered->map(function ($vc) {
            return [
                'variable' => $vc->variable_name,
                'operation' => $vc->operation,
                'value' => $vc->value,
                'context' => $vc->context,
            ];
        })->values()->toArray();
    }

    /**
     * Detect if a menu is a "function menu" (chapter select, gallery, etc.)
     * rather than a normal gameplay choice menu.
     *
     * Function menus are identified by:
     * - Label names containing keywords like "chapter", "gallery", "select", "menu_main"
     * - Prompt text indicating chapter/scene selection
     * - Choice text patterns like "Chapter X", "Scene Y", "CG Gallery"
     */
    private function isFunctionMenu(string $labelName, $choices, ?string $prompt): bool
    {
        // Check label name patterns
        $labelPatterns = [
            '/chapter[_\s]?select/i',
            '/chapter[_\s]?menu/i',
            '/chapitre[_\s]?(?:select|selec|menu)/i',
            '/(?:selection|sélection)[_\s]?chapitre/i',
            '/gallery|galerie/i',
            '/select[_\s]?screen/i',
            '/main[_\s]?menu/i',
            '/extras/i',
            '/bonus/i',
        ];
        foreach ($labelPatterns as $pattern) {
            if (preg_match($pattern, $labelName)) {
                return true;
            }
        }

        // Check prompt text patterns
        if ($prompt) {
            $promptPatterns = [
                '/^(select|choose)\s+(a\s+)?chapter/i',
                '/^(select|choose)\s+(a\s+)?scene/i',
                '/^(choisir|sélectionner|selectionner)\s+(un\s+|une\s+)?chapitre/i',
                '/^chapter\s+select/i',
                '/^chapitre\s+(select|sélection|selection)/i',
                '/^scene\s+select/i',
                '/^jump\s+to/i',
            ];
            foreach ($promptPatterns as $pattern) {
                if (preg_match($pattern, trim($prompt))) {
                    return true;
                }
            }
        }

        // Check if all choices look like chapter/scene selectors
        if ($choices->count() > 5) {
            $chapterLikeChoices = 0;
            foreach ($choices as $choice) {
                $text = $choice->text ?? '';
                // Match patterns like "Chapter 1", "Chapitre 1", "Scene 5",
                // "Prologue", "Epilogue", "Day 1", "Route A".
                if (preg_match('/^(chapter|chapitre|scene|scène|day|jour|route|part|partie|act|acte)\s*\d+/i', $text) ||
                    preg_match('/^(prologue|epilogue|épilogue|intro|ending|fin|bonus|extra|gallery|galerie|cg)/i', $text)) {
                    $chapterLikeChoices++;
                }
            }
            // If >80% of choices look like chapter selectors, it's likely a function menu
            if ($chapterLikeChoices / $choices->count() > 0.8) {
                return true;
            }
        }

        return false;
    }
}
