<?php

declare(strict_types=1);

namespace App\Services;

use App\Models\GameVersion;
use Illuminate\Support\Collection;

class RouteGraphService
{
    private const GRAPH_REVISION = 25;

    public function __construct(
        private readonly RouteGraphConditionService $conditions = new RouteGraphConditionService,
        private readonly RouteGraphPostProcessor $postProcessor = new RouteGraphPostProcessor,
        private readonly RouteGraphVariableChangeFormatter $variableChangeFormatter = new RouteGraphVariableChangeFormatter,
        private readonly RouteGraphEdgePruner $edgePruner = new RouteGraphEdgePruner,
        private readonly RouteGraphFunctionMenuDetector $functionMenuDetector = new RouteGraphFunctionMenuDetector,
        private readonly RouteGraphIdFactory $ids = new RouteGraphIdFactory,
        private readonly RouteGraphChoiceAccessor $choiceAccessor = new RouteGraphChoiceAccessor,
        private readonly RouteGraphMenuSequencer $menuSequencer = new RouteGraphMenuSequencer,
        private readonly RouteGraphMenuAnalyzer $menuAnalyzer = new RouteGraphMenuAnalyzer,
    ) {}

    /**
     * Compute word counts per label from dialogue lines.
     * Uses the game's source language, falling back to English.
     *
     * @return array<string, int> label name => word count
     */
    public static function getWordCountsByLabel(GameVersion $version): array
    {
        return app(RouteGraphWordCountService::class)->byLabel($version);
    }

    public function buildGraph(GameVersion $version, bool $includeUnreachable = false): array
    {
        if ($includeUnreachable) {
            return $this->computeGraph($version, includeUnreachable: true);
        }

        if (is_array($version->route_graph_data) && ($version->route_graph_data['graph_revision'] ?? null) === self::GRAPH_REVISION) {
            return $version->route_graph_data;
        }

        // Compute and store if not pre-calculated or if the cached graph was
        // generated by an older plotting revision.
        return $this->computeAndStore($version);
    }

    public function computeAndStore(GameVersion $version): array
    {
        $graph = $this->computeGraph($version);
        $version->route_graph_data = $graph;
        $version->saveQuietly();

        return $graph;
    }

    public function computeGraph(GameVersion $version, bool $includeUnreachable = false): array
    {
        $labels = $version->routeLabels()->get();
        $edges = $version->routeEdges()->get();
        $menuChoices = $version->routeMenuChoices()->get();
        $variables = $version->routeVariables()->get();
        $variableChanges = $version->routeVariableChanges()->get();

        $wordCounts = self::getWordCountsByLabel($version);

        // Pre-index menu choices by from_label:target_label for O(1) lookup.
        $choiceLookup = [];
        foreach ($menuChoices as $mc) {
            if (! empty($mc->target_label)) {
                $choiceLookup[$mc->from_label.':'.$mc->target_label][] = $mc;
            }
        }

        $edges = $this->edgePruner->removeInputRetrySelfLoopEdges($edges);
        $edges = $this->edgePruner->removeUnreachableFallthroughEdges($edges, $choiceLookup);
        $edgeMapByFrom = $edges->groupBy('from_label');

        // Pre-index variable changes by label AND by context for fast lookup
        $varChangesByContext = [];
        foreach ($variableChanges as $vc) {
            $key = $vc->label.'|'.($vc->context ?? '');
            $varChangesByContext[$key][] = $vc;
        }
        $varChangesByLabel = $variableChanges->groupBy('label');
        $choicesByLabel = $menuChoices->groupBy('from_label');
        $labelNames = $labels->pluck('name')->flip();

        $nodes = [];
        $processedEdges = [];
        $expandedLabels = [];
        $expandedEdgeReplacements = [];
        $expandedEndingReplacements = [];
        $additionalEndingNodes = [];

        foreach ($labels as $label) {
            $name = $label->name;
            $outgoingEdges = $edgeMapByFrom->get($name, collect());
            $isStart = $name === 'labels.start' || $name === 'start';
            $varChanges = $varChangesByLabel->get($name, collect());
            $nodeChoices = $choicesByLabel->get($name, collect());
            $continuationEdges = $outgoingEdges
                ->filter(fn ($e) => $e->edge_type !== 'menu_choice')
                ->reject(fn ($e) => $this->edgePruner->isDuplicateMenuChoiceEdge($e, $choiceLookup[$e->from_label.':'.$e->to_label] ?? []))
                ->values();
            $allTargetlessChoices = $this->menuAnalyzer->targetlessChoices($nodeChoices);
            $menuChoiceLines = $nodeChoices
                ->pluck('line_number')
                ->filter(fn ($line) => $line !== null && (int) $line > 0)
                ->map(fn ($line) => (int) $line)
                ->unique()
                ->sort()
                ->values();

            $menuGroups = $this->menuAnalyzer->meaningfulMenuGroups(
                $name,
                $this->menuAnalyzer->menuChoiceGroups($nodeChoices),
                $varChangesByContext,
                $label,
                $nodeChoices,
                $menuChoiceLines,
                $continuationEdges,
                $allTargetlessChoices
            );
            $meaningfulChoices = collect($menuGroups)
                ->flatMap(fn (array $group) => $group['choices'])
                ->values();

            // Only collapse "function menus" (chapter select, gallery, etc.) into hub nodes.
            // Normal gameplay menus should always expand to show all choices.
            // Function menus are detected by label names, prompts, or choice patterns.
            $maxExpandedChoices = 10;

            $singleGroup = count($menuGroups) === 1 ? $menuGroups[0] : null;
            $singleGroupIsFunctionMenu = $singleGroup
                ? $this->functionMenuDetector->isFunctionMenu($name, $singleGroup['choices'], $singleGroup['prompt'])
                : false;
            $shouldExpandMenus = $meaningfulChoices->isNotEmpty()
                && (count($menuGroups) > 1 || $meaningfulChoices->count() <= $maxExpandedChoices || ! $singleGroupIsFunctionMenu);

            if ($shouldExpandMenus) {
                // This label has manageable gameplay menus — expand them into sub-graphs.
                $expandedLabels[$name] = true;
                $expandedEdgeReplacements[$name] = [];
                $hasMultipleMenuGroups = count($menuGroups) > 1;
                $firstMenuCondition = $singleGroup ? $this->menuAnalyzer->commonMenuCondition($singleGroup['choices']) : null;
                $usesDedicatedMenuNodes = $hasMultipleMenuGroups || $firstMenuCondition !== null;
                [$previousMenuGroupByIndex, $nextMenuGroupByIndex] = $this->menuSequencer->menuSequenceLinks($menuGroups, $continuationEdges);
                $firstChildGroupByChoiceLine = $this->menuSequencer->firstChildMenuGroupByChoiceLine($menuGroups, $previousMenuGroupByIndex);
                $resumeGroupByChildGroupIndex = $this->menuSequencer->resumeMenuGroupByChildGroupIndex($menuGroups, $nextMenuGroupByIndex);
                foreach ($resumeGroupByChildGroupIndex as $childGroupIndex => $resumeGroupIndex) {
                    $nextMenuGroupByIndex[$childGroupIndex] ??= $resumeGroupIndex;
                }

                if ($usesDedicatedMenuNodes) {
                    $nodes[] = [
                        'id' => $name,
                        'label' => $name,
                        'node_type' => 'label',
                        'is_ending' => false,
                        'returns_to_caller' => (bool) $label->returns_to_caller,
                        'is_start' => $isStart,
                        'has_menu_choice' => false,
                        'file_path' => $label->file_path,
                        'line_number' => $label->line_number,
                        'outgoing_count' => collect(array_keys($menuGroups))
                            ->filter(fn (int $index) => ! isset($previousMenuGroupByIndex[$index]) && (int) ($menuGroups[$index]['parent_choice_line'] ?? 0) <= 0)
                            ->count(),
                        'word_count' => $wordCounts[$name] ?? 0,
                        'choices' => [],
                        'variable_changes' => $this->variableChangeFormatter->format($varChanges, excludeChoiceContexts: true),
                    ];
                }

                $targetlessChoices = $allTargetlessChoices;
                $syntheticEndingId = null;

                if ((bool) $label->is_ending) {
                    $syntheticEndingId = $this->ids->syntheticEndingId($name);
                    $expandedEndingReplacements[$name] = $syntheticEndingId;

                    if (! isset($labelNames[$syntheticEndingId])) {
                        $additionalEndingNodes[$syntheticEndingId] = [
                            'id' => $syntheticEndingId,
                            'label' => $syntheticEndingId,
                            'node_type' => 'label',
                            'is_ending' => true,
                            'returns_to_caller' => false,
                            'is_start' => false,
                            'has_menu_choice' => false,
                            'file_path' => $label->file_path,
                            'line_number' => $label->line_number,
                            'outgoing_count' => 0,
                            'word_count' => 0,
                            'choices' => [],
                            'variable_changes' => [],
                            'is_synthetic_ending' => true,
                        ];
                    }
                }

                $choiceIndex = 0;
                $choiceNodeByLine = [];

                foreach ($menuGroups as $groupIndex => $menuGroup) {
                    $groupChoices = $menuGroup['choices'];
                    $menuPrompt = $menuGroup['prompt'];
                    $menuPromptTranslations = $menuGroup['prompt_translations'];
                    $menuCondition = $usesDedicatedMenuNodes ? $this->menuAnalyzer->commonMenuCondition($groupChoices) : null;
                    $sourceId = $usesDedicatedMenuNodes
                        ? $this->menuGroupNodeId($name, $menuGroup['start_line'], $groupIndex)
                        : $name;
                    $nextMenuGroupIndex = $nextMenuGroupByIndex[$groupIndex] ?? null;
                    $nextMenuGroup = $nextMenuGroupIndex !== null ? ($menuGroups[$nextMenuGroupIndex] ?? null) : null;
                    $nextMenuSourceId = $nextMenuGroup && $usesDedicatedMenuNodes
                        ? $this->menuGroupNodeId($name, $nextMenuGroup['start_line'], $nextMenuGroupIndex)
                        : null;
                    $nextMenuCondition = $nextMenuGroup && $usesDedicatedMenuNodes
                        ? $this->menuAnalyzer->commonMenuCondition($nextMenuGroup['choices'])
                        : null;
                    $isFunctionMenu = $this->functionMenuDetector->isFunctionMenu($name, $groupChoices, $menuPrompt);
                    $renderAsHub = $groupChoices->count() > $maxExpandedChoices && $isFunctionMenu;

                    $nodes[] = [
                        'id' => $sourceId,
                        'label' => $usesDedicatedMenuNodes ? 'Menu' : $name,
                        'node_type' => $renderAsHub ? 'hub' : 'label',
                        'is_ending' => false,
                        'returns_to_caller' => (bool) $label->returns_to_caller,
                        'is_start' => ! $usesDedicatedMenuNodes && $isStart,
                        'has_menu_choice' => true,
                        'hub_choice_count' => $renderAsHub ? $groupChoices->count() : null,
                        'menu_prompt' => $menuPrompt,
                        'menu_prompt_translations' => $menuPromptTranslations,
                        'file_path' => $groupChoices->first()?->file_path ?? $label->file_path,
                        'line_number' => $menuGroup['menu_line'] ?: ($menuGroup['start_line'] ?: $label->line_number),
                        'outgoing_count' => $groupChoices->count(),
                        'word_count' => $usesDedicatedMenuNodes ? 0 : ($wordCounts[$name] ?? 0),
                        'choices' => $renderAsHub ? $groupChoices->map(fn ($mc) => [
                            'text' => $mc->text,
                            'translations' => $mc->translations,
                            'target_label' => $mc->target_label,
                            'condition' => $this->conditions->deduplicatedContinuationCondition($menuCondition, $this->menuAnalyzer->choiceCondition($mc)),
                        ])->values()->toArray() : [],
                        'variable_changes' => $usesDedicatedMenuNodes ? [] : $this->variableChangeFormatter->format($varChanges, excludeChoiceContexts: true),
                        'parent_label' => $usesDedicatedMenuNodes ? $name : null,
                    ];

                    if ($usesDedicatedMenuNodes && ! isset($previousMenuGroupByIndex[$groupIndex])) {
                        $entrySourceId = $name;
                        $entryEdgeType = 'menu';
                        $parentChoiceLine = (int) ($menuGroup['parent_choice_line'] ?? 0);

                        if ($parentChoiceLine > 0 && isset($choiceNodeByLine[$parentChoiceLine])) {
                            $entrySourceId = $choiceNodeByLine[$parentChoiceLine];
                            $entryEdgeType = 'flow';
                        }

                        $processedEdges[] = [
                            'id' => $entrySourceId.':'.$sourceId.':menu',
                            'source' => $entrySourceId,
                            'target' => $sourceId,
                            'edge_type' => $entryEdgeType,
                            'condition' => $menuCondition,
                            'condition_stack' => $menuGroup['condition_stack'] ?? [],
                        ];
                    }

                    if ($nextMenuSourceId !== null) {
                        $emptyMenuCondition = $this->menuAnalyzer->menuEmptyCondition($groupChoices);
                        if ($emptyMenuCondition !== null) {
                            $processedEdges[] = [
                                'id' => $sourceId.':'.$nextMenuSourceId.':menu_empty',
                                'source' => $sourceId,
                                'target' => $nextMenuSourceId,
                                'edge_type' => 'flow',
                                'condition' => $emptyMenuCondition,
                            ];
                        }
                    }

                    if ($renderAsHub) {
                        $choiceIndex += $groupChoices->count();

                        continue;
                    }

                    foreach ($groupChoices->values() as $mc) {
                        $choiceId = $name.':choice_'.$choiceIndex;
                        $choiceIndex++;
                        $choiceText = $mc->text ?? 'Choice '.$choiceIndex;

                        // Get variable changes for this specific choice (indexed lookup)
                        $choiceContext = 'menu_choice:'.($mc->text ?? '');
                        $contextKey = $name.'|'.$choiceContext;
                        $choiceVarChanges = $this->menuAnalyzer->getVariableChangesForChoice(
                            $mc,
                            collect($varChangesByContext[$contextKey] ?? []),
                            $nodeChoices
                        );

                        // Build label with variable effects
                        $choiceKnownCondition = $this->menuAnalyzer->choiceEffectiveCondition($mc);
                        $varSummary = $choiceVarChanges->map(function ($vc) use ($choiceKnownCondition) {
                            $summary = $vc->variable_name.' '.$vc->operation.' '.$this->variableChangeFormatter->formatValue($vc->value);
                            $condition = $this->variableChangeFormatter->displayCondition($vc, $choiceKnownCondition);

                            return $condition ? 'if '.$condition.': '.$summary : $summary;
                        })->join(', ');

                        $choiceLine = (int) ($mc->line_number ?? 0);
                        $childGroupIndex = $choiceLine > 0 ? ($firstChildGroupByChoiceLine[$choiceLine] ?? null) : null;
                        $childGroup = $childGroupIndex !== null ? ($menuGroups[$childGroupIndex] ?? null) : null;
                        $childMenuCondition = $childGroup ? $this->menuAnalyzer->commonMenuCondition($childGroup['choices']) : null;
                        $childResumeGroupIndex = $childGroupIndex !== null ? ($resumeGroupByChildGroupIndex[$childGroupIndex] ?? null) : null;
                        $childResumeGroup = $childResumeGroupIndex !== null ? ($menuGroups[$childResumeGroupIndex] ?? null) : null;
                        $childResumeSourceId = $childResumeGroup && $usesDedicatedMenuNodes
                            ? $this->menuGroupNodeId($name, $childResumeGroup['start_line'], $childResumeGroupIndex)
                            : null;
                        $hasChildMenu = $childGroup !== null && $usesDedicatedMenuNodes;
                        $childSkipCondition = $hasChildMenu ? $this->conditions->negatedCondition($childMenuCondition) : null;
                        $childResumeCondition = $childResumeGroup ? $this->menuAnalyzer->commonMenuCondition($childResumeGroup['choices']) : null;
                        $childResumeSkip = $childResumeCondition !== null && $childResumeGroup
                            ? $this->menuSequencer->commonContinuationAfterGroup($childResumeGroup, $continuationEdges)
                            : null;
                        $childSkipTargetId = $childResumeSkip['target'] ?? $childResumeSourceId;
                        $nextMenuSkip = $nextMenuCondition !== null && $nextMenuGroup
                            ? $this->menuSequencer->commonContinuationAfterGroup($nextMenuGroup, $continuationEdges)
                            : null;

                        // Hard choice: has its own target. Soft choice: uses continuation edges.
                        $hasHardTarget = ! empty($mc->target_label);
                        $choiceContinuationEdges = $hasHardTarget || $hasChildMenu
                            ? collect()
                            : $this->menuAnalyzer->getContinuationEdgesForChoice(
                                $mc,
                                $continuationEdges,
                                $targetlessChoices,
                                $nextMenuGroup ? (int) ($nextMenuGroup['start_line'] ?? 0) : null
                            );
                        $continuesToNextMenu = ! $hasHardTarget && ! $hasChildMenu && $choiceContinuationEdges->isEmpty() && $nextMenuSourceId !== null;
                        $continuesToChildSkip = ! $hasHardTarget && $hasChildMenu && $childSkipCondition !== null && $childSkipTargetId !== null;
                        $continuesPastConditionalNextMenu = ! $hasHardTarget && ! $hasChildMenu && $nextMenuSkip !== null;
                        $usesSyntheticEnding = ! $hasHardTarget && ! $hasChildMenu && ! $continuesToNextMenu && $choiceContinuationEdges->isEmpty() && $syntheticEndingId !== null;
                        $outCount = $hasHardTarget
                            ? 1
                            : ($hasChildMenu ? 1 + ($continuesToChildSkip ? 1 : 0) : (($continuesToNextMenu ? 1 : 0) + ($continuesPastConditionalNextMenu ? 1 : 0) + ($usesSyntheticEnding ? 1 : 0) + ($continuesToNextMenu || $usesSyntheticEnding ? 0 : $choiceContinuationEdges->count())));

                        $nodes[] = [
                            'id' => $choiceId,
                            'label' => $choiceText,
                            'choice_text' => $choiceText,
                            'translations' => $mc->translations,
                            'var_summary' => $varSummary ?: null,
                            'node_type' => 'choice',
                            'is_ending' => false,
                            'is_start' => false,
                            'has_menu_choice' => false,
                            'file_path' => $mc->file_path,
                            'line_number' => $mc->line_number ?? 0,
                            'outgoing_count' => $outCount,
                            'word_count' => 0,
                            'choices' => [],
                            'variable_changes' => $this->variableChangeFormatter->format($choiceVarChanges, onlyContext: $choiceContext),
                            'parent_label' => $name,
                            'condition' => $this->menuAnalyzer->choiceCondition($mc),
                        ];

                        if ($choiceLine > 0) {
                            $choiceNodeByLine[$choiceLine] = $choiceId;
                        }

                        // Edge from the menu node to the choice
                        $processedEdges[] = [
                            'id' => $sourceId.':'.$choiceId.':choice',
                            'source' => $sourceId,
                            'target' => $choiceId,
                            'edge_type' => 'choice',
                            'condition' => $this->conditions->deduplicatedContinuationCondition($menuCondition, $this->menuAnalyzer->choiceCondition($mc)),
                        ];

                        if ($hasHardTarget) {
                            // Hard choice: direct edge to its target
                            $processedEdges[] = [
                                'id' => $choiceId.':'.$mc->target_label.':choice_target',
                                'source' => $choiceId,
                                'target' => $mc->target_label,
                                'edge_type' => 'choice_target',
                                'condition' => null,
                            ];
                        } else {
                            // Soft choice: connect only to continuation edges in the
                            // same menu segment. Connecting every targetless choice
                            // to every later label-level edge creates impossible
                            // route fanout for setup/chapter-select labels.
                            if ($hasChildMenu) {
                                if ($continuesToChildSkip) {
                                    $processedEdges[] = [
                                        'id' => $choiceId.':'.$childSkipTargetId.':child_menu_empty',
                                        'source' => $choiceId,
                                        'target' => $childSkipTargetId,
                                        'edge_type' => 'flow',
                                        'condition' => $childSkipCondition,
                                    ];

                                    foreach (($childResumeSkip['edges'] ?? collect()) as $skipEdge) {
                                        $expandedEdgeReplacements[$name][$this->ids->edgeIdentity($skipEdge)] = true;
                                    }
                                }
                            } elseif ($continuesToNextMenu) {
                                $processedEdges[] = [
                                    'id' => $choiceId.':'.$nextMenuSourceId.':menu_sequence',
                                    'source' => $choiceId,
                                    'target' => $nextMenuSourceId,
                                    'edge_type' => 'flow',
                                    'condition' => $this->conditions->deduplicatedMenuTransitionCondition(
                                        $menuCondition,
                                        $this->menuAnalyzer->choiceEffectiveCondition($mc),
                                        $nextMenuCondition
                                    ),
                                    'condition_stack' => $nextMenuGroup['condition_stack'] ?? [],
                                ];

                                if ($continuesPastConditionalNextMenu) {
                                    $processedEdges[] = [
                                        'id' => $choiceId.':'.$nextMenuSkip['target'].':conditional_menu_skip',
                                        'source' => $choiceId,
                                        'target' => $nextMenuSkip['target'],
                                        'edge_type' => 'flow',
                                        'condition' => $this->conditions->negatedCondition($nextMenuCondition),
                                    ];

                                    foreach ($nextMenuSkip['edges'] as $skipEdge) {
                                        $expandedEdgeReplacements[$name][$this->ids->edgeIdentity($skipEdge)] = true;
                                    }
                                }
                            } elseif ($usesSyntheticEnding) {
                                $processedEdges[] = [
                                    'id' => $choiceId.':'.$syntheticEndingId.':return',
                                    'source' => $choiceId,
                                    'target' => $syntheticEndingId,
                                    'edge_type' => 'return',
                                    'condition' => null,
                                ];
                            } else {
                                foreach ($choiceContinuationEdges as $ce) {
                                    $processedEdges[] = [
                                        'id' => $this->ids->generatedChoiceEdgeId($choiceId, $ce),
                                        'source' => $choiceId,
                                        'target' => $ce->to_label,
                                        'edge_type' => $ce->edge_type,
                                        'condition' => $this->conditions->deduplicatedContinuationCondition($this->menuAnalyzer->choiceEffectiveCondition($mc), $ce->condition),
                                    ];

                                    if (! $this->menuAnalyzer->isOuterConditionJoinEdge($mc, $ce)) {
                                        $expandedEdgeReplacements[$name][$this->ids->edgeIdentity($ce)] = true;
                                    }
                                }
                            }
                        }
                    }
                }
            } elseif ($meaningfulChoices->count() > $maxExpandedChoices) {
                // Too many choices to expand — render as a hub node
                // Don't mark as expanded so original edges are kept
                $nodes[] = [
                    'id' => $name,
                    'label' => $name,
                    'node_type' => 'hub',
                    'is_ending' => (bool) $label->is_ending,
                    'returns_to_caller' => (bool) $label->returns_to_caller,
                    'is_start' => $isStart,
                    'has_menu_choice' => true,
                    'hub_choice_count' => $meaningfulChoices->count(),
                    'file_path' => $label->file_path,
                    'line_number' => $label->line_number,
                    'outgoing_count' => $outgoingEdges->count(),
                    'word_count' => $wordCounts[$name] ?? 0,
                    'choices' => $meaningfulChoices->map(fn ($mc) => [
                        'text' => $mc->text,
                        'translations' => $mc->translations,
                        'target_label' => $mc->target_label,
                        'condition' => $this->menuAnalyzer->choiceCondition($mc),
                    ])->values()->toArray(),
                    'variable_changes' => $this->variableChangeFormatter->format($varChanges, excludeChoiceContexts: true),
                ];
            } else {
                // Regular node without choices
                $nodes[] = [
                    'id' => $name,
                    'label' => $name,
                    'node_type' => 'label',
                    'is_ending' => (bool) $label->is_ending,
                    'returns_to_caller' => (bool) $label->returns_to_caller,
                    'is_start' => $isStart,
                    'has_menu_choice' => false,
                    'file_path' => $label->file_path,
                    'line_number' => $label->line_number,
                    'outgoing_count' => $outgoingEdges->count(),
                    'word_count' => $wordCounts[$name] ?? 0,
                    'choices' => [],
                    'variable_changes' => $this->variableChangeFormatter->format($varChanges, excludeChoiceContexts: true),
                ];
            }
        }

        foreach ($additionalEndingNodes as $node) {
            $nodes[] = $node;
        }

        // Process edges. Expanded labels keep original edges unless a generated
        // choice edge already represents that exact raw edge.
        foreach ($edges as $edge) {
            if (isset($expandedLabels[$edge->from_label])) {
                if ($edge->edge_type === 'menu_choice') {
                    continue;
                }

                $edgeKey = $this->ids->edgeIdentity($edge);
                if (isset($expandedEdgeReplacements[$edge->from_label][$edgeKey])) {
                    continue;
                }

                if ($this->edgePruner->isDuplicateMenuChoiceEdge($edge, $choiceLookup[$edge->from_label.':'.$edge->to_label] ?? [])) {
                    continue;
                }
            }

            if ($this->edgePruner->isDuplicateMenuChoiceEdge($edge, $choiceLookup[$edge->from_label.':'.$edge->to_label] ?? [])) {
                continue;
            }

            $edgeData = [
                'id' => $this->ids->routeEdgeId($edge),
                'source' => $edge->from_label,
                'target' => $edge->to_label,
                'edge_type' => $edge->edge_type,
                'condition' => $edge->condition,
                'file_path' => $edge->file_path,
                'line_number' => $edge->line_number,
            ];

            if ($edge->edge_type === 'menu_choice') {
                $matchingChoice = $this->edgePruner->findMatchingMenuChoice($edge, $choiceLookup[$edge->from_label.':'.$edge->to_label] ?? []);
                if ($matchingChoice) {
                    $edgeData['choice_text'] = $matchingChoice->text;
                    $edgeData['condition'] = $matchingChoice->condition;
                }
            }

            $processedEdges[] = $edgeData;
        }

        // Post-process: infer else conditions and deduplicate
        $processedEdges = $this->postProcessor->inferElseConditions($processedEdges);
        $processedEdges = $this->conditions->normalizeDisplayConditions($processedEdges);
        [$nodes, $processedEdges] = $this->postProcessor->factorConditionScopeEdges($nodes, $processedEdges);
        $nodes = $this->postProcessor->addMissingEndpointNodes($nodes, $processedEdges);
        if (! $includeUnreachable) {
            [$nodes, $processedEdges] = $this->postProcessor->filterReachableFromStart($nodes, $processedEdges);
        }

        // Leave disconnected script components disconnected. Fabricated bridge
        // edges make the map claim routes exist when Ren'Py control flow does
        // not actually connect them.

        return app(RouteGraphResultBuilder::class)->build(
            $nodes,
            $processedEdges,
            $variables,
            $variableChanges,
            $labels,
            $expandedEndingReplacements,
            $includeUnreachable,
            self::GRAPH_REVISION
        );
    }

    public function buildSimplifiedGraph(Collection $labels, Collection $edges, array $wordCounts = []): array
    {
        return app(RouteGraphSimplifier::class)->build($labels, $edges, $wordCounts);
    }

    private function menuGroupNodeId(string $labelName, int $startLine, int $index): string
    {
        return $labelName.':menu_'.($startLine > 0 ? $startLine : $index);
    }
}
