#!/usr/bin/env python3
"""
Convert Yarn Spinner script files to Ren'Py JSON format.

This script parses Yarn Spinner .txt script files and converts them
to the JSON format generated by json_stats.rpy for visual novel analysis.

Usage:
    python yarn_to_renpy.py <input_dir_or_file> [output.json]
    python yarn_to_renpy.py TextAsset/ output.json
    python yarn_to_renpy.py Scene0_Opening.txt output.json
"""

import argparse
import json
import re
import sys
from collections import defaultdict
from pathlib import Path


def clean_yarn_tags(text: str) -> str:
    """Remove Yarn Spinner markup tags from text."""
    if not text:
        return text

    # Remove expression/animation hashtags: #eyes:surprised #mouth:gasp_closed
    text = re.sub(r'\s*#\w+:\w+', '', text)
    # Remove simple hashtags: #blush #wet #exclamation_mark
    text = re.sub(r'\s*#\w+', '', text)

    # Remove waitfor and other command tags: <waitfor=0.5>, <pause>, etc.
    text = re.sub(r'<waitfor=[^>]*>', '', text)
    text = re.sub(r'<pause[^>]*>', '', text)
    text = re.sub(r'<wait[^>]*>', '', text)

    # Remove effect tags but preserve content: <i>text</i> -> text
    text = re.sub(r'</?i>', '', text)
    text = re.sub(r'</?b>', '', text)
    text = re.sub(r'</?em>', '', text)
    text = re.sub(r'</?strong>', '', text)
    text = re.sub(r'</?shake>', '', text)

    # Remove color tags: <color=#FFFFFF>text</color>
    text = re.sub(r'</?color[^>]*>', '', text)

    # Remove any remaining custom tags
    text = re.sub(r'<[^>]+>', '', text)

    return text.strip()


def parse_dialogue_line(line: str) -> tuple[str, str, str] | None:
    """
    Parse a Yarn Spinner dialogue line into character and text.

    Returns:
        tuple: (character_id, display_name, dialogue_text) or None if not dialogue
    """
    if not line:
        return None

    # Skip command lines
    if line.startswith('<<') or line.startswith('//'):
        return None

    # Skip lines that are only dots (wait indicators)
    if re.match(r'^[\s.]+$', line):
        return None

    # Check if line starts with a character name (format: "Character: text")
    # Character names can be: "Red", "Nico", "???", etc.
    match = re.match(r'^([^:]{1,30}):\s+(.+)$', line)

    if match:
        character_name = match.group(1).strip()
        text = match.group(2).strip()

        # Clean the text of tags
        text = clean_yarn_tags(text)

        # Skip if text is empty after cleaning or just dots
        if not text or re.match(r'^[\s.]+$', text):
            return None

        # Preserve display name as-is from the source
        display_name = character_name

        # Convert character name to a valid ID (lowercase, underscores)
        character_id = re.sub(r'\s+', '_', character_name.lower())
        # Handle special characters in names like "???"
        character_id = re.sub(r'[^a-z0-9_?]', '', character_id)
        # Convert remaining special chars to readable ID
        if '?' in character_id:
            character_id = 'unknown'

        # If ID is empty after cleanup, use fallback
        if not character_id:
            character_id = 'unknown'

        return character_id, display_name, text
    else:
        # No character prefix - check if it's narrator text (not a command)
        text = clean_yarn_tags(line)

        # Skip if empty or just dots/whitespace
        if not text or re.match(r'^[\s.]+$', text):
            return None

        return "narrator", "Narrator", text


def parse_yarn_script(filepath: Path) -> tuple[str, list[dict]]:
    """
    Parse a Yarn Spinner .txt script file and extract dialogue entries.

    Returns:
        tuple: (scene_title, list of dialogue entries)
    """
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    entries = []
    scene_title = filepath.stem  # Default to filename

    lines = content.split('\n')
    in_header = True
    line_number = 0

    for line in lines:
        line_number += 1
        stripped = line.strip()

        # Parse header
        if in_header:
            if stripped.startswith('title:'):
                scene_title = stripped[6:].strip()
                continue
            elif stripped == '---':
                in_header = False
                continue
            elif stripped == '===':
                break
            continue

        # End of script
        if stripped == '===':
            break

        # Skip empty lines
        if not stripped:
            continue

        # Skip command lines (<<...>>)
        if stripped.startswith('<<'):
            continue

        # Skip comment lines
        if stripped.startswith('//'):
            continue

        # Parse dialogue line
        result = parse_dialogue_line(stripped)
        if result:
            character_id, display_name, text = result
            entries.append({
                "character": character_id,
                "display_name": display_name,
                "text": text,
                "file": filepath.name,
                "line": line_number,
                "context": scene_title
            })

    return scene_title, entries


def parse_yarn_directory(dirpath: Path) -> list[dict]:
    """
    Parse all Yarn Spinner .txt files in a directory.

    Returns:
        list: Combined list of all dialogue entries with scene context
    """
    all_entries = []

    # Find all .txt files and sort by scene number
    txt_files = sorted(dirpath.glob('*.txt'), key=lambda p: p.name)

    for filepath in txt_files:
        scene_title, entries = parse_yarn_script(filepath)
        all_entries.extend(entries)
        print(f"  Parsed {filepath.name}: {len(entries)} entries ({scene_title})")

    return all_entries


def build_renpy_json(entries: list[dict], language: str = "default") -> dict:
    """
    Build Ren'Py JSON format from parsed dialogue entries.

    Args:
        entries: List of dialogue entries
        language: Language code

    Returns:
        dict: JSON structure matching json_stats.rpy output
    """
    # Track character statistics
    character_stats = defaultdict(lambda: {"blocks": 0, "words": 0})
    dialogue_lines = []

    # Track unique character display names (use first occurrence)
    character_display_names = {}

    for entry in entries:
        char_id = entry["character"]
        text = entry["text"]

        # Count statistics
        word_count = len(text.split()) if text else 0
        character_stats[char_id]["blocks"] += 1
        character_stats[char_id]["words"] += word_count

        # Use display name from entry (preserves original like "???")
        if char_id not in character_display_names:
            character_display_names[char_id] = entry.get("display_name", char_id)

        # Build dialogue line entry
        dialogue_lines.append({
            "character": char_id,
            "text": text,
            "file": entry["file"],
            "line": entry["line"],
            "context": entry.get("context")
        })

    # Calculate totals
    total_blocks = sum(s["blocks"] for s in character_stats.values())
    total_words = sum(s["words"] for s in character_stats.values())

    # Build character info with display names
    characters = {}
    for char_id, stats in character_stats.items():
        characters[char_id] = {
            "display_name": character_display_names.get(char_id, char_id),
            "blocks": stats["blocks"],
            "words": stats["words"]
        }

    # Build final structure
    result = {
        "languages": {
            language: {
                "blocks": total_blocks,
                "words": total_words,
                "menus": 0,
                "options": 0,
                "characters": characters
            }
        },
        "file_statistics": {
            "image": {},
            "audio": {},
            "video": {},
            "other": {},
            "summary": {
                "total_image": 0,
                "total_audio": 0,
                "total_video": 0,
                "total_other": 0,
                "total_size": 0
            }
        },
        "dialogue_lines": {
            language: dialogue_lines
        }
    }

    return result


def convert_yarn_to_renpy(input_path: Path, output_path: Path | None = None,
                          language: str = "default") -> dict:
    """
    Convert Yarn Spinner script file(s) to Ren'Py JSON format.

    Args:
        input_path: Path to input .txt file or directory
        output_path: Optional path for output JSON file
        language: Language code for the output

    Returns:
        dict: The converted JSON data
    """
    # Parse input
    if input_path.is_dir():
        print(f"Parsing Yarn scripts from directory: {input_path}")
        entries = parse_yarn_directory(input_path)
    else:
        print(f"Parsing Yarn script: {input_path}")
        _, entries = parse_yarn_script(input_path)

    # Build Ren'Py JSON
    result = build_renpy_json(entries, language)

    # Write output if path specified
    if output_path:
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(result, f, indent=4, ensure_ascii=False)
        print(f"\nConverted {len(entries)} dialogue entries to {output_path}")

    return result


def main():
    parser = argparse.ArgumentParser(
        description="Convert Yarn Spinner script files to Ren'Py JSON format"
    )
    parser.add_argument(
        "input",
        type=Path,
        help="Input Yarn Spinner .txt file or directory containing .txt files"
    )
    parser.add_argument(
        "output",
        type=Path,
        nargs="?",
        help="Output JSON file (default: stats.json)"
    )
    parser.add_argument(
        "-l", "--language",
        default="default",
        help="Language code for output (default: 'default')"
    )
    parser.add_argument(
        "-q", "--quiet",
        action="store_true",
        help="Suppress progress output"
    )

    args = parser.parse_args()

    # Determine output path
    output_path = args.output or Path("stats.json")

    try:
        result = convert_yarn_to_renpy(args.input, output_path, args.language)

        if not args.quiet:
            lang_data = result["languages"][args.language]
            print(f"\nStatistics:")
            print(f"  Total dialogue blocks: {lang_data['blocks']}")
            print(f"  Total words: {lang_data['words']}")
            print(f"  Characters: {len(lang_data['characters'])}")
            print("\nCharacter breakdown:")
            for char_id, char_data in sorted(lang_data["characters"].items(),
                                             key=lambda x: -x[1]["blocks"]):
                print(f"  {char_data['display_name']}: {char_data['blocks']} blocks, "
                      f"{char_data['words']} words")

    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
