project_name: fvn.li
language: php
ignored_paths:
- /.phpunit.cache
- /.pnpm-store
- /bootstrap/ssr
- /itchbot
- /node_modules
- /public/build
- /public/hot
- /public/storage
- /public/sitemap.xml
- /storage/*.key
- /storage/logs
- /storage/pail
- /vendor
- .env
- .env.backup
- .env.production
- .phpactor.json
- .phpunit.result.cache
- Homestead.json
- Homestead.yaml
- auth.json
- li.fvn.psql.gz
- npm-debug.log
- yarn-error.log
- /auth.json
- /.fleet
- /.idea
- /.nova
- /.vscode
- /.zed
- /caddy
- /stats.html
- frankenphp
- frankenphp-worker.php
- .aider*
- /Writerside/artifacts/
- /Writerside/.idea/
- database/**/*.sqlite*
- .ddev/.gitignore
- .ddev/**/*.example
- .ddev/.dbimageBuild
- .ddev/.ddev-docker-*.yaml
- .ddev/.*downloads
- .ddev/.homeadditions
- .ddev/.importdb*
- .ddev/.sshimageBuild
- .ddev/.webimageBuild
- .ddev/apache/apache-site.conf
- .ddev/commands/.gitattributes
- .ddev/config.local.y*ml
- .ddev/config.*.local.y*ml
- .ddev/db_snapshots
- .ddev/mutagen/mutagen.yml
- .ddev/mutagen/.start-synced
- .ddev/postgres/postgresql.conf
- .ddev/providers/acquia.yaml
- .ddev/providers/lagoon.yaml
- .ddev/providers/pantheon.yaml
- .ddev/providers/platform.yaml
- .ddev/providers/upsun.yaml
- .ddev/sequelpro.spf
- .ddev/traefik/config/fvn-li.yaml
- .ddev/traefik/certs/fvn-li.crt
- .ddev/traefik/certs/fvn-li.key
- .ddev/xhprof/xhprof_prepend.php
- .ddev/**/README.*
- .serena/cache
- .ddev/web-build/**/playwright
- .ddev/web-build/**/Dockerfile.playwright
- bootstrap/cache/**/*
- '!bootstrap/cache/**/.gitignore'
- storage/framework/**/compiled.php
- storage/framework/**/config.php
- storage/framework/**/down
- storage/framework/**/events.scanned.php
- storage/framework/**/maintenance.php
- storage/framework/**/routes.php
- storage/framework/**/routes.scanned.php
- storage/framework/**/schedule-*
- storage/framework/**/services.json
- storage/app/**/*
- '!storage/app/**/public/'
- '!storage/app/**/.gitignore'
- storage/clockwork/**/*.json
- storage/clockwork/**/*.json.gz
- storage/clockwork/**/index
- storage/framework/testing/**/*
- '!storage/framework/testing/**/.gitignore'
- storage/framework/sessions/**/*
- '!storage/framework/sessions/**/.gitignore'
- storage/framework/views/**/*
- '!storage/framework/views/**/.gitignore'
- storage/framework/cache/**/*
- '!storage/framework/cache/**/data/'
- '!storage/framework/cache/**/.gitignore'
- storage/app/public/**/*
- '!storage/app/public/**/.gitignore'
- storage/framework/cache/data/**/*
- '!storage/framework/cache/data/**/.gitignore'
read_only: false
ignore_all_files_in_gitignore: true
initial_prompt: ''
encoding: utf-8
lsp_enabled: true
lsp_auto_start: true
