#!/bin/sh
#ddev-generated

cd test/playwright || exit 1

if [ -f bun.lock ]; then
  bun && bun playwright "$@"
elif [ -f yarn.lock ]; then
  yarn && yarn playwright "$@"
else
  npx playwright "$@"
fi
