services:
  playwright:
    container_name: ddev-${DDEV_SITENAME}-playwright
    image: mcr.microsoft.com/playwright:v1.61.1-noble@sha256:5b8f294aff9041b7191c34a4bab3ac270157a28774d4b0660e9743297b697e48
    init: true
    ipc: host
    working_dir: /home/pwuser
    user: pwuser
    command:
      - /bin/sh
      - -c
      - npx -y playwright@1.61.1 run-server --port 3000 --host 0.0.0.0
    expose:
      - "3000"
    external_links:
      - ddev-router:${DDEV_HOSTNAME}
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
