#ddev-generated
services:
  redis:
    container_name: ddev-${DDEV_SITENAME}-redis
    image: redis:8.10.0@sha256:a7efd4ed5037dcfe1543c0e50b9f06293d3e88827005544bf37f381eea5f01cf
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
      - ".:/mnt/ddev_config"
      - "ddev-global-cache:/mnt/ddev-global-cache"
      - "./redis:/usr/local/etc/redis"
      - "redis:/data"
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

volumes:
  redis:
