#ddev-generated
services:
  redis:
    container_name: ddev-${DDEV_SITENAME}-redis
    image: redis:8.10.0@sha256:344e3945a0b431c8ff1eecd58c5573538126bd756f02fc7e218ddf1fc2546366
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
      - ".:/mnt/ddev_config"
      - "ddev-global-cache:/mnt/ddev-global-cache"
      - "./redis:/usr/local/etc/redis"
      - "redis:/data"
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

volumes:
  redis:
