#ddev-generated
services:
  redis:
    container_name: ddev-${DDEV_SITENAME}-redis
    image: redis:8.10.2@sha256:d5ac52db24d4e70566fe9944f22cf5bdc2bc739b05c0f426335161ea6c23f3b3
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
      - ".:/mnt/ddev_config"
      - "ddev-global-cache:/mnt/ddev-global-cache"
      - "./redis:/usr/local/etc/redis"
      - "redis:/data"
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

volumes:
  redis:
